---
- name: Create storage directories
  become: yes
  file:
    path: "{{ data_dir }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ paperless_uid }}"
    group: "{{ paperless_gid }}"
  with_items:
    - data
    - media
    - postgres
    - export
    - consume

- name: Copy Docker Compose definition file
  template:
    src: docker-compose.yml
    dest: "{{ data_dir }}/docker-compose.yml"
    mode: "0644"

- name: Start the stack with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ data_dir }}"
    pull: true
    remove_orphans: yes
