---
- name: Create storage directory
  become: yes
  file:
    path: "{{ data_dir }}/traefik"
    state: directory
    mode: "0755"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Copy Docker Compose definition file
  template:
    src: docker-compose.yml
    dest: "{{ data_dir }}/docker-compose.yml"
    mode: "0644"

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ proxy_traefik_network }}"

- name: Start the stack with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ data_dir }}"
    pull: true
    remove_orphans: yes
