# {{ ansible_managed | comment(decoration="# ") }}
---
version: "2.4"

networks:
  "{{ minio_proxy_network }}":
    external: true

services:
  minio:
    image: minio/minio:RELEASE.2022-01-08T03-11-54Z
    restart: unless-stopped
    command:
      - "server"
      - "/data"
      - --console-address
      - ":9001"
    environment:
      - MINIO_ROOT_USER={{ minio_root_user }}
      - MINIO_ROOT_PASSWORD={{ minio_root_password }}
      - MINIO_SERVER_URL=https://{{ minio_proxy_host }}
      - MINIO_BROWSER_REDIRECT_URL=https://{{ minio_proxy_console_host }}
    volumes:
      - "{{ data_dir }}/minio:/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.minio.rule: "Host(`{{ minio_proxy_host }}`)"
      traefik.http.routers.minio.entrypoints: "{{ minio_proxy_entrypoint }}"
      traefik.http.routers.minio.service: minio
      traefik.http.services.minio.loadbalancer.server.port: 9000
      traefik.http.routers.minio-console.rule: "Host(`{{ minio_proxy_console_host }}`)"
      traefik.http.routers.minio-console.entrypoints: "{{ minio_proxy_console_entrypoint }}"
      traefik.http.routers.minio-console.service: minio-console
      traefik.http.services.minio-console.loadbalancer.server.port: 9001
    networks:
      - "{{ minio_proxy_network }}"
