# {{ ansible_managed | comment(decoration="# ") }}
---
version: "2.4"

services:
  smtp:
    build:
      context: https://github.com/adventurousway/smtp-to-sendgrid-gateway.git
    restart: unless-stopped
    container_name: smtp
    environment:
      SENDGRID_API: "{{ sendgrid_api_key }}"
      SMTP_PORT: "25"
    ports:
      - "25:25/tcp"
