---
- name: Install package dependencies
  become: true
  package:
    name:
      - btrfs-progs
    state: latest

- name: Create storage directory
  become: true
  file:
    path: "{{ data_dir }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  with_items:
    - transcode
    - config

- name: Mount the media volume
  become: true
  ansible.posix.mount:
    src: "{{ plex_media_disk }}"
    path: "{{ plex_media_dir }}"
    state: mounted
    fstype: btrfs
    opts: subvol=media

- name: Copy Docker Compose definition file
  template:
    src: docker-compose.yml
    dest: "{{ data_dir }}/docker-compose.yml"
    mode: "0644"

- name: Start the stack with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ data_dir }}"
    pull: true
    remove_orphans: yes
