# {{ ansible_managed | comment(decoration="# ") }}
---
version: "2.4"

networks:
  "{{ wikijs_proxy_network }}":
    external: true
  default:
    internal: true

services:
  wikijs:
    image: requarks/wiki:2
    depends_on:
      - mariadb
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.wikijs.rule: "Host(`{{ wikijs_proxy_host }}`)"
      traefik.http.routers.wikijs.entrypoints: "{{ wikijs_proxy_entrypoint }}"
      traefik.http.services.wikijs.loadbalancer.server.port: 3000
    environment:
      - TZ={{ TZ }}
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=wikijs
      - DB_PASS={{ wikijs_db_password }}
      - DB_NAME=wiki
    networks:
      - "{{ wikijs_proxy_network }}"
      - "default"

  mariadb:
    image: mariadb:10.7.1
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wikijs
      - MYSQL_PASSWORD={{ wikijs_db_password }}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - "{{ data_dir }}/mariadb:/var/lib/mariadb"
    networks:
      - "default"
